/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavBufferPool */

#ifndef _Included_bits_jav_util_JavBufferPool
#define _Included_bits_jav_util_JavBufferPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavBufferPool
 * Method:    nInit
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavBufferPool_nInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavBufferPool
 * Method:    nGet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavBufferPool_nGet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavBufferPool
 * Method:    nUninit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_util_JavBufferPool_nUninit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
