/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_codec_JavCodec */

#ifndef _Included_bits_jav_codec_JavCodec
#define _Included_bits_jav_codec_JavCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nFindEncoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodec_nFindEncoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nFindDecoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodec_nFindDecoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nCapabilities
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nCapabilities
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSupportedFramerateCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nSupportedFramerateCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSupportedFramerate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodec_nSupportedFramerate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nPixelFormatCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nPixelFormatCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nPixelFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nPixelFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSampleRateCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nSampleRateCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSampleRate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nSampleRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSampleFormatCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nSampleFormatCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nSampleFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nSampleFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nChannelLayoutCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodec_nChannelLayoutCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nChannelLayout
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodec_nChannelLayout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodec
 * Method:    nPrivClass
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodec_nPrivClass
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
