/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_codec_JavCodecContext */

#ifndef _Included_bits_jav_codec_JavCodecContext
#define _Included_bits_jav_codec_JavCodecContext
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_jav_codec_JavCodecContext_FF_CODER_TYPE_VLC
#define bits_jav_codec_JavCodecContext_FF_CODER_TYPE_VLC 0L
#undef bits_jav_codec_JavCodecContext_FF_CODER_TYPE_AC
#define bits_jav_codec_JavCodecContext_FF_CODER_TYPE_AC 1L
#undef bits_jav_codec_JavCodecContext_FF_CODER_TYPE_RAW
#define bits_jav_codec_JavCodecContext_FF_CODER_TYPE_RAW 2L
#undef bits_jav_codec_JavCodecContext_FF_CODER_TYPE_RLE
#define bits_jav_codec_JavCodecContext_FF_CODER_TYPE_RLE 3L
#undef bits_jav_codec_JavCodecContext_FF_CODER_TYPE_DEFLATE
#define bits_jav_codec_JavCodecContext_FF_CODER_TYPE_DEFLATE 4L
#undef bits_jav_codec_JavCodecContext_FF_COMPRESSION_DEFAULT
#define bits_jav_codec_JavCodecContext_FF_COMPRESSION_DEFAULT -1L
/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nAlloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nAlloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nOpen
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nOpen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nDecodeVideo
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nDecodeVideo
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nEncodeVideo
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nEncodeVideo
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nDecodeAudio
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nDecodeAudio
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nEncodeAudio
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nEncodeAudio
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFlush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFlush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTimeBase
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nTimeBase__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTimeBase
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nTimeBase__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleAspectRatio
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nSampleAspectRatio__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleAspectRatio
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nSampleAspectRatio__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nPrivDataPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nPrivDataPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nExtraData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nExtraData__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nExtraDataSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nExtraDataSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nExtraData
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nExtraData__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCodecType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nCodecType__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCodecType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nCodecType__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCodecId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nCodecId__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCodecId
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nCodecId__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCodecName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_codec_JavCodecContext_nCodecName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nBitRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nBitRate__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nBitRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nBitRate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSize__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSize__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFlags__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFlags__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFlags2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFlags2__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFlags2
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFlags2__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nPixFmt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nPixFmt__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nPixFmt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nPixFmt__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleFmt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nSampleFmt__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleFmt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nSampleFmt__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nWidth__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nWidth__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nHeight__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nHeight__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nChannels__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nChannels
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nChannels__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nChannelLayout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nChannelLayout__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nChannelLayout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nChannelLayout__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nSampleRate__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nSampleRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nSampleRate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nGopSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nGopSize__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nGopSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nGopSize__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxBFrames
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMaxBFrames__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxBFrames
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMaxBFrames__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nKeyintMin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nKeyintMin__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nKeyintMin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nKeyintMin__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nProfile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nProfile__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nProfile
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nProfile__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nLevel__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nLevel__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nBitRateTolerance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nBitRateTolerance__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nBitRateTolerance
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nBitRateTolerance__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nGlobalQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nGlobalQuality__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nGlobalQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nGlobalQuality__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCompressionLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nCompressionLevel__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCompressionLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nCompressionLevel__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRefcountedFrames
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRefcountedFrames__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRefcountedFrames
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRefcountedFrames__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQcompress
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nQcompress__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQcompress
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nQcompress__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQblur
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nQblur__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQblur
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nQblur__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQmin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nQmin__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQmin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nQmin__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQmax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nQmax__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nQmax
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nQmax__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxQdiff
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMaxQdiff__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxQdiff
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMaxQdiff__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nScenechangeThreshold
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nScenechangeThreshold__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nScenechangeThreshold
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nScenechangeThreshold__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMeMethod__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeMethod
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMeMethod__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeRange
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMeRange__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeRange
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMeRange__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeCmp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMeCmp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeCmp
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMeCmp__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeSubCmp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMeSubCmp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMeSubCmp
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMeSubCmp__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCoderType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nCoderType__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nCoderType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nCoderType__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nContextModel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nContextModel__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nContextModel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nContextModel__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLmin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nLmin__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLmin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nLmin__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLmax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nLmax__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nLmax
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nLmax__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipThreshold
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipThreshold__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipThreshold
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipThreshold__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipFactor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipFactor__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipFactor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipFactor__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipExp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipExp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipExp
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipExp__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipCmp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipCmp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nFrameSkipCmp
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nFrameSkipCmp__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTrellis
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nTrellis__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTrellis
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nTrellis__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMinPredictionOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMinPredictionOrder__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMinPredictionOrder
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMinPredictionOrder__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxPredictionOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nMaxPredictionOrder__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nMaxPredictionOrder
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nMaxPredictionOrder__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTimecodeFrameStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavCodecContext_nTimecodeFrameStart__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nTimecodeFrameStart
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nTimecodeFrameStart__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcEq
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_codec_JavCodecContext_nRcEq__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcEq
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcEq__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQsquish
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcQsquish
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQSquint
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcQSquint
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQmodAmp
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcQmodAmp__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQmodAmp
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcQmodAmp__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQmodFreq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcQmodFreq__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcQmodFreq
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcQmodFreq__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcBufferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcBufferSize__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcBufferSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcBufferSize__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcOverrideCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcOverrideCount__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcOverrideCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcOverrideCount__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMaxRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcMaxRate__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMaxRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcMaxRate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMinRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcMinRate__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMinRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcMinRate__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcBufferAggressivity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcBufferAggressivity__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcBufferAggressivity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcBufferAggressivity__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcInitialCplx
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcInitialCplx__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcInitialCplx
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcInitialCplx__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMaxAvailableVbvUse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcMaxAvailableVbvUse__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMaxAvailableVbvUse
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcMaxAvailableVbvUse__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMinVbvOverflowUse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_bits_jav_codec_JavCodecContext_nRcMinVbvOverflowUse__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcMinVbvOverflowUse
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcMinVbvOverflowUse__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcInitialBufferOccupancy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavCodecContext_nRcInitialBufferOccupancy__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavCodecContext
 * Method:    nRcInitialBufferOccupancy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavCodecContext_nRcInitialBufferOccupancy__JI
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
