/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavChannelLayout */

#ifndef _Included_bits_jav_util_JavChannelLayout
#define _Included_bits_jav_util_JavChannelLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    get
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavChannelLayout_get
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getString
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavChannelLayout_getString
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getNbChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavChannelLayout_getNbChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getDefault
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavChannelLayout_getDefault
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getChannelIndex
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavChannelLayout_getChannelIndex
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    extractChannel
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavChannelLayout_extractChannel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getChannelName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavChannelLayout_getChannelName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getChannelDescription
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavChannelLayout_getChannelDescription
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getStandardValue
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavChannelLayout_getStandardValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavChannelLayout
 * Method:    getStandardName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavChannelLayout_getStandardName
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
