/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavDict */

#ifndef _Included_bits_jav_util_JavDict
#define _Included_bits_jav_util_JavDict
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_jav_util_JavDict_MATCH_CASE
#define bits_jav_util_JavDict_MATCH_CASE 1L
#undef bits_jav_util_JavDict_IGNORE_SUFFIX
#define bits_jav_util_JavDict_IGNORE_SUFFIX 2L
#undef bits_jav_util_JavDict_DONT_STRDUP_KEY
#define bits_jav_util_JavDict_DONT_STRDUP_KEY 4L
#undef bits_jav_util_JavDict_DONT_STRDUP_VAL
#define bits_jav_util_JavDict_DONT_STRDUP_VAL 8L
#undef bits_jav_util_JavDict_DONT_OVERWRITE
#define bits_jav_util_JavDict_DONT_OVERWRITE 16L
#undef bits_jav_util_JavDict_APPEND
#define bits_jav_util_JavDict_APPEND 32L
/*
 * Class:     bits_jav_util_JavDict
 * Method:    nGet
 * Signature: (JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavDict_nGet
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavDict_nCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nSet
 * Signature: (JLjava/lang/String;Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavDict_nSet
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jlongArray);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nCopy
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavDict_nCopy
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_util_JavDict_nFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nKey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavDict_nKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavDict
 * Method:    nValue
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavDict_nValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
