/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_JavException */

#ifndef _Included_bits_jav_JavException
#define _Included_bits_jav_JavException
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_jav_JavException_serialVersionUID
#define bits_jav_JavException_serialVersionUID -3042686055658047285LL
#undef bits_jav_JavException_serialVersionUID
#define bits_jav_JavException_serialVersionUID -3387516993124229948LL
#undef bits_jav_JavException_serialVersionUID
#define bits_jav_JavException_serialVersionUID 7818375828146090155LL
/*
 * Class:     bits_jav_JavException
 * Method:    errStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_JavException_errStr
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
