/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_format_JavFormatContext */

#ifndef _Included_bits_jav_format_JavFormatContext
#define _Included_bits_jav_format_JavFormatContext
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_jav_format_JavFormatContext_TYPE_INPUT
#define bits_jav_format_JavFormatContext_TYPE_INPUT 0L
#undef bits_jav_format_JavFormatContext_TYPE_OUTPUT
#define bits_jav_format_JavFormatContext_TYPE_OUTPUT 1L
/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nAlloc
  (JNIEnv *, jclass);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nStreamCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nStreamCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nStreamPointer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nStreamPointer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nFilename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_format_JavFormatContext_nFilename__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nFilename
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nFilename__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nMetadata
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nMetadata__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nMetadata
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nMetadata__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nDurationEstimationMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nDurationEstimationMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nAvio
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nAvio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nFindBestStream
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nFindBestStream
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOpenInput
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nOpenInput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nCloseInput
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nCloseInput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nReadFrame
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nReadFrame
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nSeekFrame
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nSeekFrame
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nSeekFile
 * Signature: (JIJJJI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nSeekFile
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jint);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOutputFormat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nOutputFormat__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOutputFormat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nOutputFormat__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nNewStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavFormatContext_nNewStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOpenOutput
 * Signature: ([JLjava/lang/String;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nOpenOutput
  (JNIEnv *, jclass, jlongArray, jstring, jlong, jstring);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOpenOutputFile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nOpenOutputFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nWriteHeader
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nWriteHeader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nWriteFrame
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nWriteFrame
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nWriteInterleavedFrame
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nWriteInterleavedFrame
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nWriteTrailer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nWriteTrailer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nOutFormatFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavFormatContext_nOutFormatFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nCloseOutputFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nCloseOutputFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavFormatContext
 * Method:    nFreeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavFormatContext_nFreeContext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
