/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_format_JavIOContext */

#ifndef _Included_bits_jav_format_JavIOContext
#define _Included_bits_jav_format_JavIOContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nBuffer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavIOContext_nBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nBufferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nBufferSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nBufferPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavIOContext_nBufferPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nBufferEnd
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavIOContext_nBufferEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nPos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavIOContext_nPos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nPosPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavIOContext_nPosPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nMustFlush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nMustFlush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nEofReached
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nEofReached
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nWriteFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nWriteFlag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nMaxPacketSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nMaxPacketSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nSeekable
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nSeekable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nMaxSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nMaxSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavIOContext
 * Method:    nDirect
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavIOContext_nDirect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
