/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_format_JavOutputFormat */

#ifndef _Included_bits_jav_format_JavOutputFormat
#define _Included_bits_jav_format_JavOutputFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nNextOutputFormat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavOutputFormat_nNextOutputFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nGuessFormat
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavOutputFormat_nGuessFormat
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_format_JavOutputFormat_nName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nLongName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_format_JavOutputFormat_nLongName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nMimeType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_format_JavOutputFormat_nMimeType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nExtensions
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_format_JavOutputFormat_nExtensions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nAudioCodec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavOutputFormat_nAudioCodec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nVideoCodec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavOutputFormat_nVideoCodec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nSubtitleCodec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavOutputFormat_nSubtitleCodec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavOutputFormat
 * Method:    nFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavOutputFormat_nFlags
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
