/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavOption */

#ifndef _Included_bits_jav_util_JavOption
#define _Included_bits_jav_util_JavOption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavOption
 * Method:    nFindOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nFindOption
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nNextOption
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nNextOption
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavOption_nName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nHelp
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavOption_nHelp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nMinValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bits_jav_util_JavOption_nMinValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nMaxValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bits_jav_util_JavOption_nMaxValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nDefaultString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavOption_nDefaultString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nDefaultLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nDefaultLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nDefaultDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_bits_jav_util_JavOption_nDefaultDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nDefaultRational
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nDefaultRational
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nUnit
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavOption_nUnit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionString
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavOption_nGetOptionString
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionString
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionString
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionDouble
 * Signature: (JLjava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_bits_jav_util_JavOption_nGetOptionDouble
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionDouble
 * Signature: (JLjava/lang/String;DI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionLong
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nGetOptionLong
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionLong
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionLong
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionRational
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nGetOptionRational
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionRational
 * Signature: (JLjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionRational
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionSampleFormat
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nGetOptionSampleFormat
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionSampleFormat
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionSampleFormat
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionChannelLayout
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nGetOptionChannelLayout
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionChannelLayout
 * Signature: (JLjava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionChannelLayout
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionPixelFormat
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nGetOptionPixelFormat
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionPixelFormat
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionPixelFormat
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionImageSize
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nGetOptionImageSize
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionImageSize
 * Signature: (JLjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionImageSize
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nGetOptionVideoRate
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavOption_nGetOptionVideoRate
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     bits_jav_util_JavOption
 * Method:    nSetOptionVideoRate
 * Signature: (JLjava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavOption_nSetOptionVideoRate
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
