/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_codec_JavPacket */

#ifndef _Included_bits_jav_codec_JavPacket
#define _Included_bits_jav_codec_JavPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nAlloc
  (JNIEnv *, jclass);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nInit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nInit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nFreeData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nFreeData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nAllocData
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nAllocData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nBuf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nBuf__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nBuf
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nBuf__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nBufSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nBufSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nData__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nData
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nData__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nMoveData
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nMoveData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nResetData
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nResetData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nMakeWritable
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nMakeWritable
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nCopy
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nCopy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nSize__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nSize__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nPts
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nPts__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nPts
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nPts__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nDts
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nDts__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nDts
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nDts__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nDuration
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nDuration__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nDuration
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nDuration__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nStreamIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nStreamIndex__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nStreamIndex
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nStreamIndex__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_codec_JavPacket_nFlags__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nFlags__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nPos
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nPos__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nPos
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nPos__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nConvergenceDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_codec_JavPacket_nConvergenceDuration__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_codec_JavPacket
 * Method:    nConvergenceDuration
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bits_jav_codec_JavPacket_nConvergenceDuration__JJ
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
