/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavPixelFormat */

#ifndef _Included_bits_jav_util_JavPixelFormat
#define _Included_bits_jav_util_JavPixelFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavPixelFormat
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavPixelFormat_get
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bits_jav_util_JavPixelFormat
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavPixelFormat_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavPixelFormat
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavPixelFormat_getString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
