/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavSampleFormat */

#ifndef _Included_bits_jav_util_JavSampleFormat
#define _Included_bits_jav_util_JavSampleFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    get
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_get
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavSampleFormat_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getAlt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getAlt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getBytesPerSample
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getBytesPerSample
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    isPlanar
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_bits_jav_util_JavSampleFormat_isPlanar
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getBufferSize
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getBufferSize
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    fillArrays
 * Signature: (JIIIIJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_fillArrays
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong, jintArray);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    copy
 * Signature: (JIIIIJI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_copy
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    setSilence
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_setSilence
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    nGetString
 * Signature: (Ljava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavSampleFormat_nGetString
  (JNIEnv *, jclass, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
