/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_format_JavStream */

#ifndef _Included_bits_jav_format_JavStream
#define _Included_bits_jav_format_JavStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_format_JavStream
 * Method:    nIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavStream_nIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavStream_nId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nCodecPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nCodecPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nFrameRate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nTimeBase
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nTimeBase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nStartTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nStartTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nNbFrames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nNbFrames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nDiscard
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_format_JavStream_nDiscard__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nDiscard
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_jav_format_JavStream_nDiscard__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_jav_format_JavStream
 * Method:    nMetadata
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_format_JavStream_nMetadata
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
