/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_util_JavSampleFormat */

#ifndef _Included_bits_jav_util_JavSampleFormat
#define _Included_bits_jav_util_JavSampleFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getSampleFormatName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bits_jav_util_JavSampleFormat_getSampleFormatName
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getSampleFormat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getSampleFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getAltSampleFormat
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getAltSampleFormat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getBytesPerSample
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getBytesPerSample
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    isFormatPlanar
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_bits_jav_util_JavSampleFormat_isFormatPlanar
  (JNIEnv *, jclass, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    getBufferSize
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_getBufferSize
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    fillArrays
 * Signature: (JIIIIJ[I)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_fillArrays
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong, jintArray);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    copy
 * Signature: (JIIIIJI)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_copy
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    setSilence
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_util_JavSampleFormat_setSilence
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     bits_jav_util_JavSampleFormat
 * Method:    nGetSampleFormatString
 * Signature: (Ljava/nio/ByteBuffer;III)J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_util_JavSampleFormat_nGetSampleFormatString
  (JNIEnv *, jclass, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
