/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_jav_swscale_SwsContext */

#ifndef _Included_bits_jav_swscale_SwsContext
#define _Included_bits_jav_swscale_SwsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_jav_swscale_SwsContext
 * Method:    nAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_jav_swscale_SwsContext_nAlloc
  (JNIEnv *, jclass);

/*
 * Class:     bits_jav_swscale_SwsContext
 * Method:    nInit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_swscale_SwsContext_nInit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_swscale_SwsContext
 * Method:    nConvert
 * Signature: (JJIIJ)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_swscale_SwsContext_nConvert
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong);

/*
 * Class:     bits_jav_swscale_SwsContext
 * Method:    nFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_jav_swscale_SwsContext_nFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_jav_swscale_SwsContext
 * Method:    nSetColorSpaceDetails
 * Signature: (J[II[IIIII)I
 */
JNIEXPORT jint JNICALL Java_bits_jav_swscale_SwsContext_nSetColorSpaceDetails
  (JNIEnv *, jclass, jlong, jintArray, jint, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
